### ISSUE TITLE
Add support for Visual Studio 2017

### ISSUE THREAD

**Issue by SanjaGit** [mobermeyer/DocStubsJs#15]

**Comment by MusicMonkey5555** [comment]
Any plan for this. I loved this plugin so much in VS2013 I am finding it hard to live without in VS2017. I know they added a bunch of javascript additions, but for some reason left out functionality as amazing as your plugin!

**Comment by mobermeyer** [comment]
I was debating supporting 2017 since JSDoc comment-generation was already supported, and vsdoc is no longer supported for intellisense. However, since multiple people are interested in this, I will see what is required to upgrade this to Visual Studio 2017.

Thanks

**Comment by wpcloki** [comment]
It looks like it's probably just going to need a recompile against the new targets. 
I unpacked the vsix with 7zip and changed the target range in the 'extension.vsixmanifest' from [11.0,14.0] to [11.0,15.0], packed the vsix back up, installed it, and it appears to be functioning correctly

**Comment by mobermeyer** [comment]
Thanks everyone for your help with this issue. I've decided that rather than trying to make this project responsible for yet another version of Visual Studio, it would be much easier and cleaner to create a separate project that supports Visual Studio 2017. This project can be found here: https://github.com/mobermeyer/DocStubsJs2017

There is now a new extension on the marketplace specifically for Visual Studio 2017 as well. It can be found here: https://marketplace.visualstudio.com/vsgallery/225a2b9c-ef8c-4120-b69d-db8b0eb4e454

Again, thanks for your help and feedback.
